# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details

version: 2

sensu_go_build_env: &sensu_go_build_env
  #### TEMPLATE_NOTE: go expects specific checkout path representing url
  #### expecting it in the form of
  ####   /go/src/github.com/circleci/go-tool
  ####   /go/src/bitbucket.org/circleci/go-tool
  environment:
    - SENSU_BUILD_ITERATION: 1

  working_directory: /go/src/github.com/sensu/sensu-go
  docker:
    - image: circleci/golang:1.10

jobs:
  build:
    <<: *sensu_go_build_env

    steps:
      - checkout

      # specify any bash command here prefixed with `run: `
      - run: sudo $PWD/circle-ci-setup.sh
      - run: ./build.sh lint
      - run: ./build.sh build_tools
      - run: make
      - run: find out/

      - persist_to_workspace:
          root: /go/src/github.com/
          paths:
            - sensu

  test:
    <<: *sensu_go_build_env
    steps:
      - attach_workspace:
          # Must be absolute path or relative path from working_directory
          at: /go/src/github.com
      - run: ./build.sh unit
      - run: ./build.sh integration

workflows:
  version: 2
  build_and_test:
    jobs:
      - build:
          filters:
            branches:
              only:
                - /^build\/.+/
                - /^master$/
      - test:
          requires:
            - build
          # Only build build-related branches (to test CI/CD changes) and
          # master for now.
          filters:
            branches:
              only:
                - /^build\/.+/
                - /^master$/
